radio changes and update
uagpmc/handbook pull request #18
Opened 2021-09-01 20:01 UTC by grayherm

2021-09-02 23:32 UTC, MrFlufficans requested changes
Seems solid to me, has very few "errors"

2021-09-02 23:32 UTC, MrFlufficans commented on docs/3-advanced-techniques/17-advanced-radio-procedures.md
>  3. Always acknowledge that you **recieved and understood** the order given.
I before E except after C <3

2021-09-02 23:32 UTC, MrFlufficans commented on docs/3-advanced-techniques/17-advanced-radio-procedures.md
> +4. If your last message had the **wrong information**, **correct it immediately** and **send** again.
If we want to be fancy I would say "incorrect information"

2021-09-02 23:32 UTC, MrFlufficans commented on docs/3-advanced-techniques/17-advanced-radio-procedures.md
> +During an operation, you will have to switch your push to talk between the different radios in order talk on each individual radio channels (you will always hear from all the radios even those you ar
missing a "to" I believe after order 

*radios in order to talk on each individual radio channels*

2021-09-09 20:39 UTC, Luigikissme approved these changes
im not good at spelling so thats on you but the info seems to be right to my knowledge

2021-09-09 20:47 UTC, MrFlufficans approved these changes
Corrected all the problems I mentioned, Looks good to me

2021-09-09 20:50 UTC, zuedev approved these changes

2021-09-09 20:50 UTC, merged